#if !canImport(ObjectiveC)
import XCTest

extension SocietyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SocietyTests = [
        ("testNothing", testNothing),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SocietyTests.__allTests__SocietyTests),
    ]
}
#endif
